-- RemoteLingo Database Schema
-- 复制这整个文件的内容，粘贴到 Supabase SQL Editor 并执行

-- 创建 jobs 表
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- 基础信息
  title TEXT NOT NULL,
  company TEXT NOT NULL,
  logo TEXT DEFAULT 'RL',
  color TEXT DEFAULT 'bg-blue-600',

  -- 语言要求
  languages TEXT[] NOT NULL,
  level TEXT DEFAULT 'Fluent',

  -- 薪资信息
  salary_min INTEGER NOT NULL,
  salary_max INTEGER NOT NULL,
  currency TEXT DEFAULT 'USD',

  -- 地点和类型
  location TEXT NOT NULL,
  type TEXT NOT NULL,

  -- 职位详情
  tags TEXT[] DEFAULT '{}',
  apply_url TEXT,
  description TEXT,

  -- 元数据
  posted_at TEXT DEFAULT 'Just now',
  featured BOOLEAN DEFAULT FALSE,

  -- AI 字段
  ai_verified BOOLEAN DEFAULT FALSE,
  source TEXT DEFAULT 'Manual',
  match_score INTEGER DEFAULT 85,
  summary TEXT,

  -- 时间戳
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 启用行级安全 (RLS)
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;

-- 创建策略：允许所有人读取
CREATE POLICY "Public jobs are viewable by everyone"
  ON jobs FOR SELECT
  USING (TRUE);

-- 创建策略：允许插入（暂时开放，后续可改为仅认证用户）
CREATE POLICY "Anyone can insert jobs"
  ON jobs FOR INSERT
  WITH CHECK (TRUE);

-- 创建 updated_at 自动更新触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_jobs_updated_at
  BEFORE UPDATE ON jobs
  FOR EACH ROW
  EXECUTE PROCEDURE update_updated_at_column();

-- 创建索引以优化查询性能
CREATE INDEX IF NOT EXISTS jobs_languages_idx ON jobs USING GIN(languages);
CREATE INDEX IF NOT EXISTS jobs_type_idx ON jobs(type);
CREATE INDEX IF NOT EXISTS jobs_featured_idx ON jobs(featured);
CREATE INDEX IF NOT EXISTS jobs_created_at_idx ON jobs(created_at DESC);

-- 插入示例数据
INSERT INTO jobs (
  title, company, logo, color, languages, level,
  salary_min, salary_max, currency, location, type,
  tags, apply_url, featured, ai_verified, source,
  match_score, summary
) VALUES
(
  'Senior Full Stack Engineer',
  'TechFlow EU',
  'TF',
  'bg-blue-600',
  ARRAY['Chinese (Mandarin)', 'English'],
  'Native/Fluent',
  75000,
  110000,
  'EUR',
  'Remote (EU Timezone)',
  'Full-time',
  ARRAY['React', 'Node.js', 'Fintech'],
  'https://example.com/apply',
  TRUE,
  TRUE,
  'Direct Career Page',
  98,
  'Requires native Mandarin for APAC banking integration team.'
),
(
  'Customer Success Manager (APAC)',
  'CloudScale',
  'CS',
  'bg-purple-600',
  ARRAY['Korean', 'English'],
  'Native',
  55000,
  80000,
  'USD',
  'Remote (Global)',
  'Contract',
  ARRAY['SaaS', 'Support', 'B2B'],
  'https://example.com/apply',
  TRUE,
  TRUE,
  'LinkedIn Verified',
  95,
  'Handling enterprise clients in Seoul. B2B SaaS experience critical.'
),
(
  'Localization Specialist & QA',
  'GameWorld',
  'GW',
  'bg-red-500',
  ARRAY['Japanese', 'English'],
  'N1/Native',
  40000,
  65000,
  'EUR',
  'Remote (Flexible)',
  'Freelance',
  ARRAY['Gaming', 'Translation', 'QA'],
  'https://example.com/apply',
  FALSE,
  FALSE,
  'Aggregated',
  88,
  'RPG game text translation and cultural adaptation.'
),
(
  'Marketing Lead (China Market)',
  'EuroLux Group',
  'EL',
  'bg-emerald-600',
  ARRAY['Chinese (Mandarin)', 'English'],
  'Native',
  80000,
  120000,
  'EUR',
  'Remote (EU/Asia Overlap)',
  'Full-time',
  ARRAY['Marketing', 'Growth', 'WeChat'],
  'https://example.com/apply',
  FALSE,
  TRUE,
  'Direct Career Page',
  92,
  'Leading brand expansion into Shanghai/Beijing markets.'
),
(
  'Technical Support Engineer',
  'SaaSify',
  'SF',
  'bg-indigo-500',
  ARRAY['German', 'English'],
  'Fluent',
  60000,
  85000,
  'USD',
  'Remote (Americas)',
  'Full-time',
  ARRAY['Support', 'API', 'Python'],
  'https://example.com/apply',
  FALSE,
  TRUE,
  'Greenhouse',
  85,
  'L2 support for DACH region customers.'
);

-- 验证数据
SELECT COUNT(*) as total_jobs FROM jobs;
SELECT title, company, languages FROM jobs ORDER BY created_at DESC;
