
// --- 1. THE INVENTORY (Real Data converted from Grok) ---
// This acts as your database for now. No SQL needed.
const JOBS_DATA = [
  // === HIGH-CONVERTING IGAMING & RELOCATION JOBS (Added for Filter Testing) ===
  {
    id: 218,
    title: "Japanese Game Presenter (Relocation to Malta)",
    company: "Evolution Gaming",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Japanese", "English"],
    level: "Entry Level",
    salary_min: 35000,
    salary_max: 45000,
    currency: "EUR",
    location: "Malta (Flight + Housing Included)",
    type: "Full-time",
    tags: ["Japanese", "No Experience", "Visa Sponsored", "Free Accommodation"],
    posted_at: "2h ago",
    featured: true,
    ai_verified: true,
    source: "Evolution Careers",
    match_score: 98,
    summary: "Native Japanese speaker needed for live studio in Malta. No coding skills required. Full relocation package included (Flight, Housing, Gym). Start immediately.",
    apply_url: "https://careers.evolution.com/"
  },
  {
    id: 219,
    title: "Korean Market Coordinator / Game Host",
    company: "Pragmatic Play",
    logoBg: "bg-indigo-800",
    initials: "PP",
    languages: ["Korean", "English"],
    level: "Entry Level",
    salary_min: 32000,
    salary_max: 40000,
    currency: "EUR",
    location: "Tbilisi, Georgia",
    type: "Full-time",
    tags: ["Korean", "Entry Level", "Visa Support", "Relocation"],
    posted_at: "4h ago",
    featured: true,
    ai_verified: true,
    source: "Pragmatic Play Careers",
    match_score: 96,
    summary: "Join our expanding team in Georgia. We are looking for energetic Korean speakers. We provide work permit support and temporary housing.",
    apply_url: "https://www.pragmaticplay.com/careers/"
  },
  {
    id: 220,
    title: "Content Moderator (Chinese Speaker)",
    company: "TikTok Trust & Safety",
    logoBg: "bg-red-800",
    initials: "TT",
    languages: ["Chinese", "English"],
    level: "Entry Level",
    salary_min: 28000,
    salary_max: 32000,
    currency: "EUR",
    location: "Dublin, Ireland / Lisbon, Portugal",
    type: "Full-time",
    tags: ["Chinese", "Visa Sponsored", "Social Media"],
    posted_at: "1h ago",
    featured: true,
    ai_verified: true,
    source: "TikTok Careers",
    match_score: 95,
    summary: "Review content for the Chinese market. Relocation package available for qualified candidates. Great entry-level opportunity in Tech.",
    apply_url: "https://careers.tiktok.com/"
  },
  {
    id: 221,
    title: "Customer Experience Specialist (Mandarin/Cantonese)",
    company: "Agoda",
    logoBg: "bg-orange-800",
    initials: "AG",
    languages: ["Chinese", "English"],
    level: "Entry Level",
    salary_min: 30000,
    salary_max: 42000,
    currency: "USD",
    location: "Remote (Global)",
    type: "Full-time",
    tags: ["Chinese", "Remote", "Customer Support"],
    posted_at: "Just now",
    featured: false,
    ai_verified: true,
    source: "Agoda Careers",
    match_score: 92,
    summary: "Fully remote role supporting travel customers. Equipment provided. Flexible shifts.",
    apply_url: "https://careersatagoda.com/"
  },

  // === EXISTING TECH & LANGUAGE JOBS ===
  {
    id: 101,
    title: "Game Presenter (Japanese/Korean)",
    company: "Evolution",
    logoBg: "bg-black",
    initials: "EVO",
    languages: ["Japanese", "Korean", "English"],
    level: "Native",
    salary_min: 30000,
    salary_max: 50000,
    currency: "EUR",
    location: "Malta (Relocation Provided)",
    type: "Full-time",
    tags: ["Visa Sponsorship", "Relocation Package", "Entry Level"],
    posted_at: "1h ago",
    featured: true,
    ai_verified: true,
    source: "Evolution Careers",
    match_score: 98,
    summary: "Includes flight tickets, 2 weeks accommodation, and full visa sponsorship. Move to Europe with no coding skills required.",
    apply_url: "https://www.evolution.com/careers"
  },
  {
    id: 109,
    title: "Game Presenter (Japanese/Korean/Russian)",
    company: "Evolution",
    logoBg: "bg-orange-600",
    initials: "EVO",
    languages: ["Japanese", "Korean", "Russian"],
    level: "Entry Level",
    salary_min: 30000,
    salary_max: 50000,
    currency: "EUR",
    location: "Malta/Latvia/Madrid/Vancouver/Georgia/Armenia (Relocation Provided)",
    type: "Full-time",
    tags: ["Gaming", "Relocation", "Visa Support"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Evolution Careers",
    match_score: 98,
    summary: "Entry-level role with relocation to Europe (Malta, Latvia, Madrid, Georgia, Armenia) or Canada (Vancouver). Includes visa sponsorship, flight tickets, initial accommodation, and bonuses. No experience or coding required. Positions available for Russian speakers in Tbilisi (Georgia) and Yerevan (Armenia). Hourly pay around €7-16 or $24.75 CAD, leading to annual 30k-50k with incentives.",
    apply_url: "https://careers.evolution.com/"
  },
  {
    id: 114,
    title: "Korean Speaking Game Presenter",
    company: "Evolution",
    logoBg: "bg-cyan-600",
    initials: "EVO",
    languages: ["Korean", "English"],
    level: "Entry Level",
    salary_min: 30000,
    salary_max: 40000,
    currency: "EUR",
    location: "Birkirkara, Malta (Relocation Provided)",
    type: "Full-time",
    tags: ["Live Casino", "Gaming", "Visa Support", "No Experience Needed"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "LinkedIn",
    match_score: 97,
    summary: "Host live casino games on camera, interacting with players in Korean and English. No prior experience required—full training provided. Enjoy relocation support to Malta including visa sponsorship and initial accommodation. Competitive salary with bonuses, perfect for outgoing bilingual talents seeking European opportunities.",
    apply_url: "https://mt.linkedin.com/jobs/view/korean-speaking-game-presenter-at-evolution-4279563333"
  },
  {
    id: 115,
    title: "Japanese & English Speaking Game Presenter",
    company: "Evolution",
    logoBg: "bg-orange-600",
    initials: "EVO",
    languages: ["Japanese", "English"],
    level: "Entry Level",
    salary_min: 30000,
    salary_max: 40000,
    currency: "EUR",
    location: "Malta (Relocation Provided)",
    type: "Full-time",
    tags: ["Live Dealer", "Casino Games", "Relocation", "Bonuses"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "LinkedIn",
    match_score: 96,
    summary: "Become the face of live casino games, hosting on camera for global players in Japanese and English. Entry-level role with no experience needed—training included. Relocation to Malta with visa, flights, and accommodation support. Earn a solid salary plus performance incentives in a dynamic international environment.",
    apply_url: "https://mt.linkedin.com/jobs/view/japanese-english-speaking-game-presenter-at-evolution-4279563314"
  },
  {
    id: 116,
    title: "Korean Speaking Online Game Presenter",
    company: "Evolution Americas",
    logoBg: "bg-orange-600",
    initials: "EVA",
    languages: ["Korean", "English"],
    level: "Entry Level",
    salary_min: 30000,
    salary_max: 45000,
    currency: "EUR",
    location: "Burnaby, BC, Canada (Relocation Possible)",
    type: "Full-time",
    tags: ["Customer Service", "Live Streaming", "Gaming", "Bonuses"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Indeed",
    match_score: 95,
    summary: "Provide customer service as a live game presenter, hosting casino games on camera in Korean. Starting at $24.75/hour plus bonuses—no experience required. Opportunity in Burnaby serving Korean, Japanese, and Chinese markets. Ideal for bilingual individuals with relocation support available for international candidates.",
    apply_url: "https://ca.indeed.com/q-chinese-game-jobs.html"
  },
  {
    id: 117,
    title: "Game Presenter with Korean",
    company: "ARRISE",
    logoBg: "bg-indigo-800",
    initials: "AR",
    languages: ["Korean", "English"],
    level: "Entry Level",
    salary_min: 25000,
    salary_max: 35000,
    currency: "EUR",
    location: "Canada (On-Site)",
    type: "Full-time",
    tags: ["Live Casino", "Communication", "No Experience", "Customer Service"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "LinkedIn",
    match_score: 94,
    summary: "Host live games on camera with fluency in Korean and English, focusing on excellent communication and customer service. No prior experience needed—must be comfortable on camera. Entry-level role in Canada with potential for bonuses and growth in the iGaming industry.",
    apply_url: "https://ca.linkedin.com/jobs/view/game-presenter-with-korean-at-arrise-4115197317"
  },
  {
    id: 1,
    title: "Bilingual Language Expert (English-Japanese)",
    company: "Mercor",
    logoBg: "bg-blue-500",
    initials: "ME",
    languages: ["Japanese", "English"],
    level: "Native",
    salary_min: 46000,
    salary_max: 64400,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Bilingual", "Translation", "AI"],
    posted_at: "Today",
    featured: true,
    ai_verified: true,
    source: "Partner Network",
    match_score: 92,
    summary: "Assess the quality and naturalness of translations, focusing on fluency, local phrasing, and cultural relevance in Japanese.",
    apply_url: "https://benture.io/job/bilingual-language-expert-english-japanese-at-mercor"
  },
  {
    id: 2,
    title: "Senior Software Engineer (Backend)",
    company: "CADDi",
    logoBg: "bg-green-500",
    initials: "CA",
    languages: ["Japanese", "English"],
    level: "Business",
    salary_min: 37200,
    salary_max: 74400,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Software Engineering", "Backend"],
    posted_at: "Today",
    featured: true,
    ai_verified: true,
    source: "Official Career Page",
    match_score: 88,
    summary: "Senior Software Engineer position at CADDi with basic Japanese OK, work from anywhere in Japan, salary up to ¥12M.",
    apply_url: "https://japan-dev.com/jobs/caddi/caddi-senior-software-engineer-backend---english-i6b8nk"
  },
  {
    id: 3,
    title: "QA Automation Lead Engineer",
    company: "Money Forward",
    logoBg: "bg-red-500",
    initials: "MF",
    languages: ["Japanese", "English"],
    level: "Business",
    salary_min: 30000,
    salary_max: 58900,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["QA", "Automation", "Engineering"],
    posted_at: "Today",
    featured: false,
    ai_verified: true,
    source: "Official Career Page",
    match_score: 85,
    summary: "Money Forward is looking for a QA Automation Lead Engineer with basic Japanese OK, partial remote work, salary up to ¥9.5M.",
    apply_url: "https://japan-dev.com/jobs/money-forward/money-forward-qa-automation-lead-engineer-money-forward-x-tokyo-aycmvk"
  },
  {
    id: 4,
    title: "Highly Skilled IT Engineer",
    company: "MORABU Hanshin Industrial",
    logoBg: "bg-yellow-500",
    initials: "MH",
    languages: ["Japanese", "English"],
    level: "N2",
    salary_min: 40000,
    salary_max: 60000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["IT", "Engineering"],
    posted_at: "Today",
    featured: false,
    ai_verified: true,
    source: "Direct Page",
    match_score: 83,
    summary: "Recruiting highly skilled IT engineers with JLPT N2, wishing to live and work in Japan for many years.",
    apply_url: "https://recruit.morabu.com/en/"
  },
  {
    id: 5,
    title: "English Localization Helper for Mobile App",
    company: "Panory",
    logoBg: "bg-purple-500",
    initials: "PA",
    languages: ["Japanese", "English"],
    level: "Native English",
    salary_min: 30000,
    salary_max: 50000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Localization", "Translation", "Mobile App"],
    posted_at: "Today",
    featured: false,
    ai_verified: false,
    source: "Social Media",
    match_score: 80,
    summary: "Looking for native English speaker who can communicate in Japanese to help with English localization of a mobile app, compensation available.",
    apply_url: "https://x.com/ObataGenta/status/1995705890683654410"
  },
  {
    id: 6,
    title: "Player Support KR/JP/EN: Night shift",
    company: "Side",
    logoBg: "bg-indigo-500",
    initials: "SI",
    languages: ["Japanese", "English"],
    level: "Fluent",
    salary_min: 30000,
    salary_max: 50000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Customer Service", "Support", "Gaming"],
    posted_at: "Today",
    featured: false,
    ai_verified: true,
    source: "LinkedIn",
    match_score: 78,
    summary: "Remote, entry-level multilingual support role for player support in Korean, Japanese, and English during night shift.",
    apply_url: "https://x.com/HitmarkerJobs/status/1997776889218486767"
  },
  {
    id: 7,
    title: "Cloud Engineer",
    company: "Large Japanese IT Company",
    logoBg: "bg-teal-500",
    initials: "LJ",
    languages: ["Japanese", "English"],
    level: "Business",
    salary_min: 24800,
    salary_max: 31000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Cloud", "Engineering", "AWS", "Azure", "GCP"],
    posted_at: "Today",
    featured: false,
    ai_verified: true,
    source: "Social Media",
    match_score: 82,
    summary: "Participate in cloud environment building, monitoring, and fault handling for AWS/Azure/GCP, with business Japanese required.",
    apply_url: "https://x.com/watomirai/status/1995721144574640161"
  },
  {
    id: 8,
    title: "Java Developer",
    company: "Ark Wiz Consulting",
    logoBg: "bg-cyan-500",
    initials: "AW",
    languages: ["Japanese", "English"],
    level: "Business",
    salary_min: 40000,
    salary_max: 60000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Java", "Spring", "SQL"],
    posted_at: "Today",
    featured: false,
    ai_verified: true,
    source: "Social Media",
    match_score: 84,
    summary: "Java basic remote job with requirements for Java (Spring) experience 3 years, basic design, SQL tuning, batch development.",
    apply_url: "https://x.com/awc_sekine/status/1996466008513777927"
  },
  {
    id: 9,
    title: "Bilingual Interpreter Translator and Assistant",
    company: "Interesse International Inc",
    logoBg: "bg-lime-500",
    initials: "II",
    languages: ["Japanese", "English"],
    level: "Fluent",
    salary_min: 30000,
    salary_max: 50000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Interpreter", "Translator"],
    posted_at: "Today",
    featured: false,
    ai_verified: true,
    source: "Job Board",
    match_score: 81,
    summary: "Candidates who enjoy helping others using Japanese are highly welcome.",
    apply_url: "https://nihongojobs.com/job/interesse-international-inc-washington-in-full-time-j-e-bilingual-interpreter-translator-and-assistant/"
  },
  {
    id: 10,
    title: "Assoc Business Administration Specialist (Bilingual Japanese)",
    company: "Nintendo of America",
    logoBg: "bg-pink-500",
    initials: "NA",
    languages: ["Japanese", "English"],
    level: "Bilingual",
    salary_min: 40000,
    salary_max: 60000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Business Administration", "Bilingual"],
    posted_at: "Today",
    featured: true,
    ai_verified: true,
    source: "Official Career Page",
    match_score: 90,
    summary: "Assoc Business Administration Specialist with bilingual Japanese skills.",
    apply_url: "https://app.careerarc.com/job_postings/6604843"
  },
  {
    id: 11,
    title: "Bilingual Language Expert (English-Korean)",
    company: "Mercor",
    logoBg: "bg-blue-500",
    initials: "ME",
    languages: ["Korean", "English"],
    level: "Native",
    salary_min: 64400,
    salary_max: 73600,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Bilingual", "Translation", "AI"],
    posted_at: "Today",
    featured: true,
    ai_verified: true,
    source: "Partner Network",
    match_score: 95,
    summary: "Bilingual Language Expert (English-Korean) for remote work worldwide.",
    apply_url: "https://benture.io/job/bilingual-language-expert-english-korean-at-mercor"
  },
  {
    id: 12,
    title: "Back End / Full Stack Developer",
    company: "SpaceVision AI, Inc.",
    logoBg: "bg-green-500",
    initials: "SA",
    languages: ["Korean", "English"],
    level: "Business",
    salary_min: 50000,
    salary_max: 100000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Backend", "Full Stack", "Python"],
    posted_at: "Today",
    featured: false,
    ai_verified: true,
    source: "Job Board",
    match_score: 87,
    summary: "Back End / Full Stack Developer position requiring business Korean.",
    apply_url: "https://dev-korea.com/jobs/spacevision-ai-inc-back-end-full-stack-developer"
  },
  {
    id: 13,
    title: "Engineering Manager, ML Data",
    company: "Twelve Labs",
    logoBg: "bg-red-500",
    initials: "TL",
    languages: ["Korean", "English"],
    level: "Business",
    salary_min: 80000,
    salary_max: 120000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Engineering", "Machine Learning", "Data"],
    posted_at: "Today",
    featured: true,
    ai_verified: true,
    source: "Job Board",
    match_score: 93,
    summary: "Engineering Manager for ML Data requiring business Korean, hybrid in Seoul.",
    apply_url: "https://dev-korea.com/jobs/twelve-labs-engineering-manager-ml-data-3b79cf3b"
  },
  {
    id: 14,
    title: "Growth Lead, Korea",
    company: "OpenAI",
    logoBg: "bg-yellow-500",
    initials: "OA",
    languages: ["Korean", "English"],
    level: "Native",
    salary_min: 100000,
    salary_max: 150000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Growth", "Marketing"],
    posted_at: "Today",
    featured: true,
    ai_verified: true,
    source: "Official Career Page",
    match_score: 96,
    summary: "Remote Growth Lead for Korea at OpenAI.",
    apply_url: "https://jobicy.com/jobs/137311-growth-lead-korea"
  },
  {
    id: 15,
    title: "Assistant/Associate/Full Professor of Computational Linguistics",
    company: "Seoul National University",
    logoBg: "bg-purple-500",
    initials: "SN",
    languages: ["Korean", "English"],
    level: "Academic",
    salary_min: 60000,
    salary_max: 100000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Computational Linguistics", "Professor"],
    posted_at: "Today",
    featured: false,
    ai_verified: true,
    source: "Academic Network",
    match_score: 89,
    summary: "Open-rank, tenure-track position in computational linguistics at Seoul National University.",
    apply_url: "https://linguistlist.org/issues/36/3725/"
  },
  {
    id: 16,
    title: "Player Support KR/JP/EN: Night shift",
    company: "Side",
    logoBg: "bg-indigo-500",
    initials: "SI",
    languages: ["Korean", "English"],
    level: "Fluent",
    salary_min: 30000,
    salary_max: 50000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Customer Service", "Support", "Gaming"],
    posted_at: "Today",
    featured: false,
    ai_verified: true,
    source: "LinkedIn",
    match_score: 78,
    summary: "Remote, entry-level multilingual support role for player support in Korean, Japanese, and English during night shift.",
    apply_url: "https://x.com/HitmarkerJobs/status/1997776889218486767"
  },
  {
    id: 17,
    title: "Localization Quality Assurance (Korean)",
    company: "Amber Studio",
    logoBg: "bg-teal-500",
    initials: "AS",
    languages: ["Korean", "English"],
    level: "Native",
    salary_min: 40000,
    salary_max: 60000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Localization", "QA", "Game Development"],
    posted_at: "Today",
    featured: false,
    ai_verified: true,
    source: "Official Career Page",
    match_score: 85,
    summary: "Localization Quality Assurance role for Korean, presencial or remote at Amber Studio.",
    apply_url: "https://jobs.jobvite.com/amber-studio"
  },
  {
    id: 18,
    title: "Translation and Content Planning",
    company: "Incheon Sondo",
    logoBg: "bg-cyan-500",
    initials: "IS",
    languages: ["Korean", "English"],
    level: "Fluent",
    salary_min: 30000,
    salary_max: 50000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Translation", "Content Planning"],
    posted_at: "Today",
    featured: false,
    ai_verified: false,
    source: "Social Media",
    match_score: 79,
    summary: "Job for translation and content planning, F visa holders, interested contact DM.",
    apply_url: "https://x.com/arinchang00/status/1996548736378704041"
  },
  {
    id: 19,
    title: "Staff for Korean Study Abroad Agent",
    company: "GOGO KOREA",
    logoBg: "bg-lime-500",
    initials: "GK",
    languages: ["Korean", "English"],
    level: "Fluent",
    salary_min: 30000,
    salary_max: 50000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Staff", "Remote Work", "Study Abroad"],
    posted_at: "Today",
    featured: false,
    ai_verified: false,
    source: "Social Media",
    match_score: 77,
    summary: "Recruiting staff for business expansion, Korean study abroad experience, work with Korean language, remote possible.",
    apply_url: "https://x.com/gogo__korea/status/1996504757125419463"
  },
  {
    id: 20,
    title: "Developer Support Engineer",
    company: "RevenueCat",
    logoBg: "bg-pink-500",
    initials: "RC",
    languages: ["Korean", "English"],
    level: "Fluent",
    salary_min: 50000,
    salary_max: 80000,
    currency: "EUR",
    location: "Remote",
    type: "Full-time",
    tags: ["Developer Support", "Android", "iOS"],
    posted_at: "Today",
    featured: false,
    ai_verified: true,
    source: "Job Board",
    match_score: 86,
    summary: "Developer Support Engineer position, no Korean required but including as per schema.",
    apply_url: "https://dev-korea.com/jobs/revenuecat-developer-support-engineer-8c0f2b99"
  },
  {
    id: 118,
    title: "Bilingual Spanish Technical Support Specialist",
    company: "SupportYourApp",
    logoBg: "bg-blue-700",
    initials: "SYA",
    languages: ["Spanish", "English"],
    level: "Entry Level",
    salary_min: 30000,
    salary_max: 45000,
    currency: "EUR",
    location: "Remote (Worldwide)",
    type: "Full-time",
    tags: ["Tech Support", "Customer Service", "Bilingual", "No Experience Needed"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Working Nomads",
    match_score: 95,
    summary: "Provide tech support to global clients in Spanish and English via chat/email. No prior experience required—full training and flexible remote setup. Enjoy bonuses for performance and work-life balance in a growing tech firm.",
    apply_url: "https://www.workingnomads.com/remote-spanish-jobs"
  },
  {
    id: 119,
    title: "Remote Bilingual French Customer Service Representative",
    company: "Concentrix",
    logoBg: "bg-purple-700",
    initials: "CX",
    languages: ["French", "English"],
    level: "Entry Level",
    salary_min: 35000,
    salary_max: 50000,
    currency: "EUR",
    location: "Remote (Europe/US)",
    type: "Full-time",
    tags: ["Customer Service", "Bilingual", "Tech", "Flexible Hours"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Indeed",
    match_score: 96,
    summary: "Handle customer inquiries for tech products in French and English from home. Entry-level with paid training, bonuses, and remote perks like home office stipend. Ideal for bilingual talents seeking stable remote work.",
    apply_url: "https://www.indeed.com/q-french-bilingual-l-remote-jobs.html"
  },
  {
    id: 120,
    title: "PHP Developer (German Speakers Welcome)",
    company: "OnTheGoSystems",
    logoBg: "bg-green-700",
    initials: "OTG",
    languages: ["German", "English"],
    level: "Mid Level",
    salary_min: 40000,
    salary_max: 60000,
    currency: "EUR",
    location: "Remote (Worldwide)",
    type: "Full-time",
    tags: ["PHP", "Development", "Multilingual", "Tech"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "We Work Remotely",
    match_score: 97,
    summary: "Develop multilingual plugins like WPML in PHP for a remote-first team. German fluency a plus for client interactions. Competitive salary, flexible hours, and growth opportunities in a global tech environment.",
    apply_url: "https://weworkremotely.com/remote-jobs/onthegosystems-php-developer-french-or-german-speakers"
  },
  {
    id: 128,
    title: "Russian Speaking Customer Care Representative",
    company: "Teleperformance Greece",
    logoBg: "bg-blue-800",
    initials: "TPG",
    languages: ["Russian", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Athens, Greece (Relocation Provided)",
    type: "Full-time",
    tags: ["Customer Service", "Call Center", "Visa Support", "Relocation Package"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "LinkedIn",
    match_score: 95,
    summary: "Provide customer support in Russian for international clients. Relocation support to Athens including visa sponsorship, flights, and accommodation. Ideal for Russian speakers seeking to move to Europe with no prior experience required.",
    apply_url: "https://gr.linkedin.com/jobs/view/russian-speaking-representatives-for-cc-roles%2Brelocation-support-at-europe-language-jobs-177094629"
  },
  {
    id: 130,
    title: "Russian Speaking Sales Associate",
    company: "LinkedIn",
    logoBg: "bg-blue-900",
    initials: "LI",
    languages: ["Russian", "English"],
    level: "Mid Level",
    salary_min: 40000,
    salary_max: 60000,
    currency: "EUR",
    location: "Dublin, Ireland (Relocation Provided)",
    type: "Full-time",
    tags: ["Sales", "Tech", "Visa Assistance", "Relocation Support"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 94,
    summary: "Support sales operations targeting Russian markets. Relocation to Dublin with visa sponsorship and assistance. Opportunity for Russian speakers to join a global tech company in Europe.",
    apply_url: "https://careers.linkedin.com/Locations#1"
  },
  {
    id: 131,
    title: "Customer Support Specialist (Russian)",
    company: "Salesforce",
    logoBg: "bg-red-800",
    initials: "SF",
    languages: ["Russian", "English"],
    level: "Entry Level",
    salary_min: 35000,
    salary_max: 50000,
    currency: "EUR",
    location: "Paris, France (Relocation Provided)",
    type: "Full-time",
    tags: ["Customer Support", "CRM", "Visa Sponsorship", "Training Provided"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 93,
    summary: "Handle customer inquiries in Russian for Salesforce products. Full relocation support to Paris, including visa and housing assistance. Great for relocating to Europe.",
    apply_url: "https://careers.salesforce.com/en/our-locations/europe-middle-east-and-africa/"
  },
  {
    id: 132,
    title: "Russian Language Operations Coordinator",
    company: "Amazon",
    logoBg: "bg-orange-800",
    initials: "AM",
    languages: ["Russian", "English"],
    level: "Mid Level",
    salary_min: 40000,
    salary_max: 55000,
    currency: "EUR",
    location: "Berlin, Germany (Relocation Provided)",
    type: "Full-time",
    tags: ["Operations", "E-commerce", "Relocation Package", "Visa Support"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 95,
    summary: "Coordinate operations for Russian-speaking markets. Relocation to Berlin with visa sponsorship and support. Ideal for Russian speakers seeking European opportunities.",
    apply_url: "https://www.amazon.jobs/en-gb/locations/?&continent=all&cache"
  },
  {
    id: 133,
    title: "Content Moderator (Russian Speaking)",
    company: "Meta",
    logoBg: "bg-blue-700",
    initials: "ME",
    languages: ["Russian", "English"],
    level: "Entry Level",
    salary_min: 30000,
    salary_max: 45000,
    currency: "EUR",
    location: "London, UK (Relocation Provided)",
    type: "Full-time",
    tags: ["Content Moderation", "Social Media", "Visa Assistance", "Bonuses"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 92,
    summary: "Moderate content in Russian on Meta platforms. Relocation support to London, including visa. Entry-level role for those wanting to move abroad.",
    apply_url: "https://www.metacareers.com/jobs/?is_leadership=0&is_in_page=0"
  },
  {
    id: 134,
    title: "Russian Speaking Software Support Engineer",
    company: "Microsoft",
    logoBg: "bg-blue-600",
    initials: "MS",
    languages: ["Russian", "English"],
    level: "Mid Level",
    salary_min: 50000,
    salary_max: 70000,
    currency: "EUR",
    location: "Prague, Czech Republic (Relocation Provided)",
    type: "Full-time",
    tags: ["Tech Support", "Software", "Relocation Support", "Visa Sponsorship"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 96,
    summary: "Provide software support in Russian. Full relocation to Prague with visa help. Opportunity for tech-savvy Russian speakers to relocate to Europe.",
    apply_url: "https://careers.microsoft.com/v2/global/en/locations.html"
  },
  {
    id: 135,
    title: "Localization Specialist (Russian)",
    company: "Netflix",
    logoBg: "bg-red-900",
    initials: "NF",
    languages: ["Russian", "English"],
    level: "Entry Level",
    salary_min: 35000,
    salary_max: 50000,
    currency: "EUR",
    location: "Amsterdam, Netherlands (Relocation Provided)",
    type: "Full-time",
    tags: ["Localization", "Entertainment", "Visa Support", "Creative Role"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 94,
    summary: "Localize content for Russian audiences. Relocation to Amsterdam with visa sponsorship. Perfect for language enthusiasts moving to Europe.",
    apply_url: "https://jobs.netflix.com/region/europe-middle-east-africa"
  },
  {
    id: 136,
    title: "Russian Speaking Energy Analyst",
    company: "BP",
    logoBg: "bg-green-900",
    initials: "BP",
    languages: ["Russian", "English"],
    level: "Mid Level",
    salary_min: 45000,
    salary_max: 65000,
    currency: "EUR",
    location: "London, UK (Relocation Provided)",
    type: "Full-time",
    tags: ["Energy", "Analysis", "Relocation Package", "Visa Assistance"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 93,
    summary: "Analyze energy markets with Russian focus. Relocation support to London, including visa. Suited for Russian speakers in energy sector relocating abroad.",
    apply_url: "https://www.bp.com/en/global/corporate/careers.html"
  },
  {
    id: 137,
    title: "Customer Experience Specialist (Russian)",
    company: "Google",
    logoBg: "bg-multicolor-900",
    initials: "GO",
    languages: ["Russian", "English"],
    level: "Entry Level",
    salary_min: 40000,
    salary_max: 55000,
    currency: "EUR",
    location: "Dublin, Ireland (Relocation Provided)",
    type: "Full-time",
    tags: ["Customer Experience", "Tech", "Visa Sponsorship", "Training"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 95,
    summary: "Improve user experience for Russian-speaking customers. Relocation to Dublin with full visa support. Great entry into tech for relocators from Russia.",
    apply_url: "https://www.google.com/about/careers/applications/jobs/results/"
  },
  {
    id: 148,
    title: "Portuguese Speaking Game Presenter (Relocation to Malta)",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 25000,
    salary_max: 35000,
    currency: "EUR",
    location: "Malta (Relocation Provided)",
    type: "Full-time",
    tags: ["Gaming", "Live Casino", "Visa Support", "Relocation"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Evolution Careers",
    match_score: 96,
    summary: "Host live casino games on camera in Portuguese. No experience needed; full training provided. Relocation package includes visa sponsorship, flights, and initial accommodation. Ideal for Portuguese speakers seeking to leave Portugal for European opportunities.",
    apply_url: "https://careers.evolution.com/"
  },
  {
    id: 149,
    title: "Portuguese Speaking Customer Support Agent",
    company: "Teleperformance",
    logoBg: "bg-blue-800",
    initials: "TP",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Athens, Greece (Relocation Provided)",
    type: "Full-time",
    tags: ["Customer Service", "Support", "Visa Sponsorship", "Flights Included"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Teleperformance Careers",
    match_score: 95,
    summary: "Provide support to Portuguese-speaking customers. Relocation to Greece with visa, flights, and accommodation support. Entry-level role for those wanting to move abroad from Portugal.",
    apply_url: "https://www.teleperformance.com/en-us/careers"
  },
  {
    id: 150,
    title: "Portuguese Speaking Content Moderator",
    company: "Majorel",
    logoBg: "bg-purple-800",
    initials: "MJ",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 22000,
    salary_max: 32000,
    currency: "EUR",
    location: "Lisbon, Portugal or Remote Europe (Relocation Options)",
    type: "Full-time",
    tags: ["Content Moderation", "Social Media", "Relocation Support", "Bonuses"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Majorel Careers",
    match_score: 94,
    summary: "Moderate content in Portuguese for global platforms. Options for relocation within Europe with support. Suitable for Portuguese speakers looking for international moves.",
    apply_url: "https://www.majorel.com/careers/"
  },
  {
    id: 151,
    title: "Portuguese Speaking Sales Representative",
    company: "Concentrix",
    logoBg: "bg-green-800",
    initials: "CX",
    languages: ["Portuguese", "English"],
    level: "Mid Level",
    salary_min: 30000,
    salary_max: 40000,
    currency: "EUR",
    location: "Barcelona, Spain (Relocation Provided)",
    type: "Full-time",
    tags: ["Sales", "B2B", "Visa Assistance", "Accommodation Support"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Concentrix Careers",
    match_score: 93,
    summary: "Handle sales for Portuguese markets. Relocation to Spain with visa and housing assistance. Opportunity for Portuguese speakers to relocate.",
    apply_url: "https://www.concentrix.com/careers/"
  },
  {
    id: 152,
    title: "Portuguese Language Translator",
    company: "Lionbridge",
    logoBg: "bg-yellow-800",
    initials: "LB",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 25000,
    salary_max: 35000,
    currency: "EUR",
    location: "Warsaw, Poland (Relocation Provided)",
    type: "Full-time",
    tags: ["Translation", "Linguistics", "Visa Support", "Training"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Lionbridge Careers",
    match_score: 92,
    summary: "Provide translation services in Portuguese. Relocation to Poland with visa sponsorship. Great for Portuguese speakers seeking new countries.",
    apply_url: "https://www.lionbridge.com/careers/"
  },
  {
    id: 153,
    title: "Portuguese Speaking Customer Experience Specialist",
    company: "Foundever",
    logoBg: "bg-red-800",
    initials: "FE",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 23000,
    salary_max: 33000,
    currency: "EUR",
    location: "Lisbon, Portugal or Athens, Greece (Relocation Options)",
    type: "Full-time",
    tags: ["Customer Experience", "Support", "Relocation Package", "Bonuses"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Foundever Careers",
    match_score: 91,
    summary: "Improve customer experience for Portuguese speakers. Relocation options with support. Suitable for those wanting to leave Portugal.",
    apply_url: "https://www.foundever.com/careers/"
  },
  {
    id: 154,
    title: "Portuguese Speaking Operations Coordinator",
    company: "Amazon",
    logoBg: "bg-orange-800",
    initials: "AM",
    languages: ["Portuguese", "English"],
    level: "Mid Level",
    salary_min: 40000,
    salary_max: 55000,
    currency: "EUR",
    location: "Berlin, Germany (Relocation Provided)",
    type: "Full-time",
    tags: ["Operations", "E-commerce", "Visa Support", "Relocation"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Amazon Jobs",
    match_score: 95,
    summary: "Coordinate operations for Portuguese markets. Relocation to Germany with full support. Opportunity for Portuguese speakers to move abroad.",
    apply_url: "https://www.amazon.jobs/en"
  },
  {
    id: 155,
    title: "Portuguese Speaking Software Support Engineer",
    company: "Microsoft",
    logoBg: "bg-blue-600",
    initials: "MS",
    languages: ["Portuguese", "English"],
    level: "Mid Level",
    salary_min: 50000,
    salary_max: 70000,
    currency: "EUR",
    location: "Prague, Czech Republic (Relocation Provided)",
    type: "Full-time",
    tags: ["Tech Support", "Software", "Visa Sponsorship", "Relocation"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Microsoft Careers",
    match_score: 96,
    summary: "Provide software support in Portuguese. Relocation to Czech Republic with visa help. Ideal for tech-savvy Portuguese speakers relocating.",
    apply_url: "https://careers.microsoft.com/"
  },
  {
    id: 156,
    title: "Portuguese Localization Specialist",
    company: "Netflix",
    logoBg: "bg-red-900",
    initials: "NF",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 35000,
    salary_max: 50000,
    currency: "EUR",
    location: "Amsterdam, Netherlands (Relocation Provided)",
    type: "Full-time",
    tags: ["Localization", "Entertainment", "Visa Support", "Creative"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Netflix Jobs",
    match_score: 94,
    summary: "Localize content for Portuguese audiences. Relocation to Netherlands with sponsorship. Perfect for language enthusiasts moving from Portugal.",
    apply_url: "https://jobs.netflix.com/"
  },
  {
    id: 157,
    title: "Portuguese Speaking Energy Analyst",
    company: "BP",
    logoBg: "bg-green-900",
    initials: "BP",
    languages: ["Portuguese", "English"],
    level: "Mid Level",
    salary_min: 45000,
    salary_max: 65000,
    currency: "EUR",
    location: "London, UK (Relocation Provided)",
    type: "Full-time",
    tags: ["Energy", "Analysis", "Relocation Package", "Visa Assistance"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "BP Careers",
    match_score: 93,
    summary: "Analyze energy markets with Portuguese focus. Relocation to UK with support. Suited for Portuguese speakers seeking international roles.",
    apply_url: "https://www.bp.com/en/global/corporate/careers.html"
  },
  {
    id: 159,
    title: "Portuguese Speaking Customer Support Specialist",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Southfield, US (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Customer Support", "Casino Dealer", "Visa Support", "No Experience Needed"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Evolution Careers",
    match_score: 95,
    summary: "Provide customer support in Portuguese for online casino. Entry-level with visa sponsorship, flights, and relocation assistance for international candidates.",
    apply_url: "https://careers.evolution.com/job/744000094922009/"
  },
  {
    id: 160,
    title: "Portuguese Speaking Live Support Specialist",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 22000,
    salary_max: 32000,
    currency: "EUR",
    location: "Burnaby, Canada (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Live Support", "Gaming", "Relocation", "Bonuses"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "SmartRecruiters",
    match_score: 94,
    summary: "Offer live support in Portuguese for gaming platforms. Relocation to Canada with visa, flights, and accommodation for Portuguese speakers seeking new opportunities.",
    apply_url: "https://careers.smartrecruiters.com/Evolution"
  },
  {
    id: 161,
    title: "Portuguese Speaking Customer Service Representative",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 23000,
    salary_max: 33000,
    currency: "EUR",
    location: "Malta (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Customer Service", "Support", "Visa Assistance", "Training Provided"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Indeed",
    match_score: 93,
    summary: "Handle customer inquiries in Portuguese. Full relocation support including visa and flights for those wanting to leave Portugal.",
    apply_url: "https://www.indeed.com/q-evolution-gaming-jobs.html"
  },
  {
    id: 162,
    title: "Portuguese Speaking Online Casino Dealer & Support",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 24000,
    salary_max: 34000,
    currency: "EUR",
    location: "US (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Casino Dealer", "Support", "Relocation Package", "No Experience"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Evolution Careers",
    match_score: 92,
    summary: "Combine dealing and support roles in Portuguese. Visa sponsorship, flights, and relocation for entry-level positions.",
    apply_url: "https://careers.evolution.com/usa/"
  },
  {
    id: 163,
    title: "Portuguese Speaking Host/Hostess Support",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 25000,
    salary_max: 35000,
    currency: "EUR",
    location: "Malta (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Host/Hostess", "Gaming Support", "Visa", "Flights"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Indeed",
    match_score: 91,
    summary: "Host games and provide support in Portuguese. Relocation with visa and flights for Portuguese speakers moving abroad.",
    apply_url: "https://www.indeed.com/q-evolution-gaming-jobs.html"
  },
  {
    id: 164,
    title: "Portuguese Speaking Customer Success Specialist",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 26000,
    salary_max: 36000,
    currency: "EUR",
    location: "Canada (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Customer Success", "Support", "Relocation", "Bonuses"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "SmartRecruiters",
    match_score: 90,
    summary: "Ensure customer success in Portuguese. Full relocation support including visa and flights.",
    apply_url: "https://careers.smartrecruiters.com/Evolution"
  },
  {
    id: 165,
    title: "Portuguese Speaking Equipment Support (Part Time)",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "US (Relocation Provided with Visa & Flights)",
    type: "Part-time",
    tags: ["Equipment Support", "Gaming", "Visa Support", "Training"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Evolution Careers",
    match_score: 89,
    summary: "Support online casino equipment in Portuguese. Part-time with relocation, visa, and flights.",
    apply_url: "https://careers.evolution.com/usa/"
  },
  {
    id: 166,
    title: "Portuguese Speaking Floor Supervisor Support",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Mid Level",
    salary_min: 30000,
    salary_max: 40000,
    currency: "EUR",
    location: "Malta (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Floor Supervisor", "Support", "Relocation", "Leadership"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Indeed",
    match_score: 88,
    summary: "Supervise and support in Portuguese. Relocation with visa and flights for mid-level roles.",
    apply_url: "https://www.indeed.com/q-evolution-gaming-jobs.html"
  },
  {
    id: 167,
    title: "Portuguese Speaking Research Support",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Mid Level",
    salary_min: 35000,
    salary_max: 45000,
    currency: "EUR",
    location: "Worldwide (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Research", "Gaming", "Visa Sponsorship", "Relocation"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "LinkedIn",
    match_score: 87,
    summary: "Provide research support in Portuguese. Global relocation with visa and flights.",
    apply_url: "https://www.linkedin.com/jobs/evolution-gaming-jobs-worldwide"
  },
  {
    id: 178,
    title: "Multilingual Game Presenter (Relocation to Malta)",
    company: "Evolution Gaming",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 25000,
    salary_max: 35000,
    currency: "EUR",
    location: "Malta (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["iGaming", "Customer Support", "Visa Sponsorship", "No Experience Needed"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Evolution Careers",
    match_score: 98,
    summary: "Host live casino games in multiple languages. Entry-level role with full visa sponsorship, flights, airport pickup, and initial accommodation. Perfect for multilingual talents seeking relocation.",
    apply_url: "https://careers.evolution.com/"
  },
  {
    id: 179,
    title: "Customer Service Representative (Multilingual, Relocation to Serbia)",
    company: "ARRISE (Pragmatic Play)",
    logoBg: "bg-indigo-800",
    initials: "AR",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Serbia (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["iGaming", "Support", "Visa Support", "Relocation Package"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "ARRISE Careers",
    match_score: 97,
    summary: "Provide support in multiple languages for iGaming. Includes visa, work permit, flights, and housing allowance. Entry-level with training for international candidates.",
    apply_url: "https://arrise.com/careers/"
  },
  {
    id: 180,
    title: "Entry-Level Game Developer Support (Relocation to Netherlands)",
    company: "Guerrilla Games",
    logoBg: "bg-red-800",
    initials: "GG",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 30000,
    salary_max: 40000,
    currency: "EUR",
    location: "Netherlands (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Gaming", "Development Support", "Visa Sponsorship", "Relocation Bonus"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Guerrilla Careers",
    match_score: 96,
    summary: "Support game development in multilingual teams. Full relocation including visa, immigration help, housing search, and bonus. Suitable for entry-level multilingual talents.",
    apply_url: "https://www.guerrilla-games.com/join"
  },
  {
    id: 181,
    title: "Multilingual Marketing Support (Relocation to Europe)",
    company: "Applike Group",
    logoBg: "bg-green-800",
    initials: "AG",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 25000,
    salary_max: 35000,
    currency: "EUR",
    location: "Europe (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Marketing", "Support", "Visa Assistance", "Relocation Support"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Applike Careers",
    match_score: 95,
    summary: "Assist in multilingual marketing. Relocation support with visa, travel, housing, and bonus. Entry-level for diverse language speakers.",
    apply_url: "https://applike-group.com/jobs/"
  },
  {
    id: 182,
    title: "Entry-Level iGaming Analyst (Relocation to Malta)",
    company: "Next Job Abroad",
    logoBg: "bg-blue-900",
    initials: "NJA",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 22000,
    salary_max: 32000,
    currency: "EUR",
    location: "Malta (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["iGaming", "Analysis", "Visa Sponsorship", "Relocation Help"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Next Job Abroad",
    match_score: 94,
    summary: "Analyze iGaming data in multiple languages. Full relocation assistance including visa, flights, and accommodation for international moves.",
    apply_url: "https://nextjobabroad.com/"
  },
  {
    id: 183,
    title: "Multilingual Customer Support (Relocation to Greece)",
    company: "Teleperformance Greece",
    logoBg: "bg-blue-800",
    initials: "TPG",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Greece (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Customer Service", "Support", "Visa Support", "No Experience"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Teleperformance Careers",
    match_score: 93,
    summary: "Handle customer inquiries in multiple languages. Relocation with visa, flights, and accommodation for entry-level roles.",
    apply_url: "https://tp-greece.com/"
  },
  {
    id: 184,
    title: "Entry-Level Content Moderator (Relocation to Europe)",
    company: "Concentrix",
    logoBg: "bg-green-800",
    initials: "CX",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 22000,
    salary_max: 32000,
    currency: "EUR",
    location: "Europe (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Content Moderation", "Support", "Visa Assistance", "Training"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Concentrix Careers",
    match_score: 92,
    summary: "Moderate content in multiple languages. Full relocation package with visa, flights, and accommodation.",
    apply_url: "https://jobs.concentrix.com/"
  },
  {
    id: 185,
    title: "Multilingual Game Development Support (Relocation to Europe)",
    company: "Ubisoft",
    logoBg: "bg-red-800",
    initials: "UB",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 30000,
    salary_max: 40000,
    currency: "EUR",
    location: "Europe (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Gaming", "Development", "Visa Sponsorship", "Relocation Bonus"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Ubisoft Careers",
    match_score: 91,
    summary: "Support game development in multiple languages. Relocation with visa, flights, and accommodation assistance.",
    apply_url: "https://www.ubisoft.com/en-us/company/careers"
  },
  {
    id: 186,
    title: "Entry-Level Multilingual Jobs (Relocation to Europe)",
    company: "Europe Language Jobs",
    logoBg: "bg-blue-900",
    initials: "ELJ",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Europe (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Various Support", "Customer Service", "Visa Support", "No Experience"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Europe Language Jobs",
    match_score: 90,
    summary: "Various multilingual entry-level roles. Relocation with visa, flights, and accommodation included.",
    apply_url: "https://www.europelanguagejobs.com/"
  },
  {
    id: 187,
    title: "Multilingual Customer Support (Relocation to Portugal)",
    company: "Job Squad",
    logoBg: "bg-purple-800",
    initials: "JS",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 22000,
    salary_max: 32000,
    currency: "EUR",
    location: "Portugal (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Customer Support", "BPO", "Visa Assistance", "Relocation Help"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Job Squad",
    match_score: 89,
    summary: "Provide multilingual customer support. Full relocation with visa, flights, and accommodation.",
    apply_url: "https://www.jobsqd.com/"
  },
  {
    id: 188,
    title: "Entry-Level Multilingual Roles (Relocation to Europe)",
    company: "Foundever",
    logoBg: "bg-red-800",
    initials: "FE",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Europe (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Support", "Customer Service", "Visa Sponsorship", "No Experience"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Foundever Careers",
    match_score: 88,
    summary: "Various multilingual entry-level support roles. Relocation package with visa, flights, and accommodation.",
    apply_url: "https://jobs.foundever.com/"
  },

  // === RUSSIAN SPEAKING POSITIONS (IDs 141-147) ===
  {
    id: 141,
    title: "Estonian and Russian Support for a Smoke-Free Future",
    company: "Not Specified (via Europe Language Jobs)",
    logoBg: "bg-purple-800",
    initials: "ELJ",
    languages: ["Russian", "Estonian", "English"],
    level: "Entry Level",
    salary_min: 23000,
    salary_max: 33000,
    currency: "EUR",
    location: "Athens, Greece (Relocation Provided)",
    type: "Full-time",
    tags: ["Customer Support", "Health", "Relocation", "Hotel Assistance"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Europe Language Jobs",
    match_score: 92,
    summary: "Support initiatives in Estonian and Russian. Includes relocation with flights and initial hotel stay. Visa sponsorship available for international moves.",
    apply_url: "https://www.europelanguagejobs.com/jobs-for-Russian-speakers"
  },
  {
    id: 142,
    title: "Tech Roles with Relocation (Multilingual)",
    company: "LinkedIn",
    logoBg: "bg-blue-900",
    initials: "LI",
    languages: ["Russian", "English"],
    level: "Mid Level",
    salary_min: 50000,
    salary_max: 70000,
    currency: "EUR",
    location: "Dublin, Ireland (Relocation Provided)",
    type: "Full-time",
    tags: ["Tech", "Engineering", "Visa Sponsorship", "Flights & Housing"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 96,
    summary: "Various tech positions suitable for multilingual speakers. Relocation includes flights, temporary hotel, and visa support. Opportunity to move to Europe.",
    apply_url: "https://careers.linkedin.com/Locations#1"
  },
  {
    id: 143,
    title: "Energy Sector Roles",
    company: "BP",
    logoBg: "bg-green-900",
    initials: "BP",
    languages: ["Russian", "English"],
    level: "Mid Level",
    salary_min: 45000,
    salary_max: 65000,
    currency: "EUR",
    location: "London, UK (Relocation Provided)",
    type: "Full-time",
    tags: ["Energy", "Analysis", "Family Support", "Flights Included"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 94,
    summary: "Roles in energy with Russian focus. Comprehensive relocation with flights, hotel, and family assistance. Visa sponsorship for international candidates.",
    apply_url: "https://www.bp.com/en/global/corporate/careers.html"
  },
  {
    id: 144,
    title: "CRM and Development Positions",
    company: "Salesforce",
    logoBg: "bg-red-800",
    initials: "SF",
    languages: ["Russian", "English"],
    level: "Entry Level",
    salary_min: 35000,
    salary_max: 50000,
    currency: "EUR",
    location: "Paris, France (Relocation Provided)",
    type: "Full-time",
    tags: ["CRM", "Development", "Visa", "Hotel Support"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 93,
    summary: "Entry-level CRM roles for multilingual. Relocation package covers flights and initial hotel stay. Great for relocating to France.",
    apply_url: "https://careers.salesforce.com/en/our-locations/europe-middle-east-and-africa/"
  },
  {
    id: 145,
    title: "Tech and Operational Roles",
    company: "Amazon",
    logoBg: "bg-orange-800",
    initials: "AM",
    languages: ["Russian", "English"],
    level: "Mid Level",
    salary_min: 40000,
    salary_max: 60000,
    currency: "EUR",
    location: "Berlin, Germany (Relocation Provided)",
    type: "Full-time",
    tags: ["E-commerce", "Operations", "Flights", "Visa Support"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 95,
    summary: "Operational roles with Russian support. Includes flights, hotel, and school fees in relocation. Visa sponsorship available.",
    apply_url: "https://www.amazon.jobs/en-gb/locations/?&continent=all&cache"
  },
  {
    id: 146,
    title: "Social Media Tech Roles",
    company: "Meta",
    logoBg: "bg-blue-700",
    initials: "ME",
    languages: ["Russian", "English"],
    level: "Entry Level",
    salary_min: 30000,
    salary_max: 45000,
    currency: "EUR",
    location: "London, UK (Relocation Provided)",
    type: "Full-time",
    tags: ["Social Media", "Development", "Visa", "Hotel Assistance"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 94,
    summary: "Entry-level tech roles for multilingual. Relocation with flights and hotel support. Focus on inclusion for international moves.",
    apply_url: "https://www.metacareers.com/jobs/?is_leadership=0&is_in_page=0"
  },
  {
    id: 147,
    title: "Software and Tech Positions",
    company: "Microsoft",
    logoBg: "bg-blue-600",
    initials: "MS",
    languages: ["Russian", "English"],
    level: "Mid Level",
    salary_min: 50000,
    salary_max: 70000,
    currency: "EUR",
    location: "Prague, Czech Republic (Relocation Provided)",
    type: "Full-time",
    tags: ["Software", "Tech Support", "Flights", "Visa Sponsorship"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Relocate.me",
    match_score: 96,
    summary: "Software support in Russian. Swift relocation with flights and hotel. Opportunity to relocate to Czech Republic.",
    apply_url: "https://careers.microsoft.com/v2/global/en/locations.html"
  },

  // === PORTUGUESE SPEAKING POSITIONS (IDs 199-217) - SECOND SET ===
  {
    id: 199,
    title: "Portuguese Speaking Game Presenter (Relocation to Malta)",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 25000,
    salary_max: 35000,
    currency: "EUR",
    location: "Malta (Relocation Provided)",
    type: "Full-time",
    tags: ["Gaming", "Live Casino", "Visa Support", "Relocation"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Evolution Careers",
    match_score: 96,
    summary: "Host live casino games on camera in Portuguese. No experience needed; full training provided. Relocation package includes visa sponsorship, flights, and initial accommodation. Ideal for Portuguese speakers seeking to leave Portugal for European opportunities.",
    apply_url: "https://careers.evolution.com/"
  },
  {
    id: 200,
    title: "Portuguese Speaking Customer Support Agent",
    company: "Teleperformance",
    logoBg: "bg-blue-800",
    initials: "TP",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Athens, Greece (Relocation Provided)",
    type: "Full-time",
    tags: ["Customer Service", "Support", "Visa Sponsorship", "Flights Included"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Teleperformance Careers",
    match_score: 95,
    summary: "Provide support to Portuguese-speaking customers. Relocation to Greece with visa, flights, and accommodation support. Entry-level role for those wanting to move abroad from Portugal.",
    apply_url: "https://www.teleperformance.com/en-us/careers"
  },
  {
    id: 201,
    title: "Portuguese Speaking Content Moderator",
    company: "Majorel",
    logoBg: "bg-purple-800",
    initials: "MJ",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 22000,
    salary_max: 32000,
    currency: "EUR",
    location: "Lisbon, Portugal or Remote Europe (Relocation Options)",
    type: "Full-time",
    tags: ["Content Moderation", "Social Media", "Relocation Support", "Bonuses"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Majorel Careers",
    match_score: 94,
    summary: "Moderate content in Portuguese for global platforms. Options for relocation within Europe with support. Suitable for Portuguese speakers looking for international moves.",
    apply_url: "https://www.majorel.com/careers/"
  },
  {
    id: 202,
    title: "Portuguese Speaking Sales Representative",
    company: "Concentrix",
    logoBg: "bg-green-800",
    initials: "CX",
    languages: ["Portuguese", "English"],
    level: "Mid Level",
    salary_min: 30000,
    salary_max: 40000,
    currency: "EUR",
    location: "Barcelona, Spain (Relocation Provided)",
    type: "Full-time",
    tags: ["Sales", "B2B", "Visa Assistance", "Accommodation Support"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Concentrix Careers",
    match_score: 93,
    summary: "Handle sales for Portuguese markets. Relocation to Spain with visa and housing assistance. Opportunity for Portuguese speakers to relocate.",
    apply_url: "https://www.concentrix.com/careers/"
  },
  {
    id: 203,
    title: "Portuguese Language Translator",
    company: "Lionbridge",
    logoBg: "bg-yellow-800",
    initials: "LB",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 25000,
    salary_max: 35000,
    currency: "EUR",
    location: "Warsaw, Poland (Relocation Provided)",
    type: "Full-time",
    tags: ["Translation", "Linguistics", "Visa Support", "Training"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Lionbridge Careers",
    match_score: 92,
    summary: "Provide translation services in Portuguese. Relocation to Poland with visa sponsorship. Great for Portuguese speakers seeking new countries.",
    apply_url: "https://www.lionbridge.com/careers/"
  },
  {
    id: 204,
    title: "Portuguese Speaking Customer Experience Specialist",
    company: "Foundever",
    logoBg: "bg-red-800",
    initials: "FE",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 23000,
    salary_max: 33000,
    currency: "EUR",
    location: "Lisbon, Portugal or Athens, Greece (Relocation Options)",
    type: "Full-time",
    tags: ["Customer Experience", "Support", "Relocation Package", "Bonuses"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Foundever Careers",
    match_score: 91,
    summary: "Improve customer experience for Portuguese speakers. Relocation options with support. Suitable for those wanting to leave Portugal.",
    apply_url: "https://www.foundever.com/careers/"
  },
  {
    id: 205,
    title: "Portuguese Speaking Operations Coordinator",
    company: "Amazon",
    logoBg: "bg-orange-800",
    initials: "AM",
    languages: ["Portuguese", "English"],
    level: "Mid Level",
    salary_min: 40000,
    salary_max: 55000,
    currency: "EUR",
    location: "Berlin, Germany (Relocation Provided)",
    type: "Full-time",
    tags: ["Operations", "E-commerce", "Visa Support", "Relocation"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Amazon Jobs",
    match_score: 95,
    summary: "Coordinate operations for Portuguese markets. Relocation to Germany with full support. Opportunity for Portuguese speakers to move abroad.",
    apply_url: "https://www.amazon.jobs/en"
  },
  {
    id: 206,
    title: "Portuguese Speaking Software Support Engineer",
    company: "Microsoft",
    logoBg: "bg-blue-600",
    initials: "MS",
    languages: ["Portuguese", "English"],
    level: "Mid Level",
    salary_min: 50000,
    salary_max: 70000,
    currency: "EUR",
    location: "Prague, Czech Republic (Relocation Provided)",
    type: "Full-time",
    tags: ["Tech Support", "Software", "Visa Sponsorship", "Relocation"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Microsoft Careers",
    match_score: 96,
    summary: "Provide software support in Portuguese. Relocation to Czech Republic with visa help. Ideal for tech-savvy Portuguese speakers relocating.",
    apply_url: "https://careers.microsoft.com/"
  },
  {
    id: 207,
    title: "Portuguese Localization Specialist",
    company: "Netflix",
    logoBg: "bg-red-900",
    initials: "NF",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 35000,
    salary_max: 50000,
    currency: "EUR",
    location: "Amsterdam, Netherlands (Relocation Provided)",
    type: "Full-time",
    tags: ["Localization", "Entertainment", "Visa Support", "Creative"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Netflix Jobs",
    match_score: 94,
    summary: "Localize content for Portuguese audiences. Relocation to Netherlands with sponsorship. Perfect for language enthusiasts moving from Portugal.",
    apply_url: "https://jobs.netflix.com/"
  },
  {
    id: 208,
    title: "Portuguese Speaking Energy Analyst",
    company: "BP",
    logoBg: "bg-green-900",
    initials: "BP",
    languages: ["Portuguese", "English"],
    level: "Mid Level",
    salary_min: 45000,
    salary_max: 65000,
    currency: "EUR",
    location: "London, UK (Relocation Provided)",
    type: "Full-time",
    tags: ["Energy", "Analysis", "Relocation Package", "Visa Assistance"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "BP Careers",
    match_score: 93,
    summary: "Analyze energy markets with Portuguese focus. Relocation to UK with support. Suited for Portuguese speakers seeking international roles.",
    apply_url: "https://www.bp.com/en/global/corporate/careers.html"
  },
  {
    id: 209,
    title: "Portuguese Speaking Customer Support Specialist",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Southfield, US (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Customer Support", "Casino Dealer", "Visa Support", "No Experience Needed"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Evolution Careers",
    match_score: 95,
    summary: "Provide customer support in Portuguese for online casino. Entry-level with visa sponsorship, flights, and relocation assistance for international candidates.",
    apply_url: "https://careers.evolution.com/job/744000094922009/"
  },
  {
    id: 210,
    title: "Portuguese Speaking Live Support Specialist",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 22000,
    salary_max: 32000,
    currency: "EUR",
    location: "Burnaby, Canada (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Live Support", "Gaming", "Relocation", "Bonuses"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "SmartRecruiters",
    match_score: 94,
    summary: "Offer live support in Portuguese for gaming platforms. Relocation to Canada with visa, flights, and accommodation for Portuguese speakers seeking new opportunities.",
    apply_url: "https://careers.smartrecruiters.com/Evolution"
  },
  {
    id: 211,
    title: "Portuguese Speaking Customer Service Representative",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 23000,
    salary_max: 33000,
    currency: "EUR",
    location: "Malta (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Customer Service", "Support", "Visa Assistance", "Training Provided"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Indeed",
    match_score: 93,
    summary: "Handle customer inquiries in Portuguese. Full relocation support including visa and flights for those wanting to leave Portugal.",
    apply_url: "https://www.indeed.com/q-evolution-gaming-jobs.html"
  },
  {
    id: 212,
    title: "Portuguese Speaking Online Casino Dealer & Support",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 24000,
    salary_max: 34000,
    currency: "EUR",
    location: "US (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Casino Dealer", "Support", "Relocation Package", "No Experience"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Evolution Careers",
    match_score: 92,
    summary: "Combine dealing and support roles in Portuguese. Visa sponsorship, flights, and relocation for entry-level positions.",
    apply_url: "https://careers.evolution.com/usa/"
  },
  {
    id: 213,
    title: "Portuguese Speaking Host/Hostess Support",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 25000,
    salary_max: 35000,
    currency: "EUR",
    location: "Malta (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Host/Hostess", "Gaming Support", "Visa", "Flights"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Indeed",
    match_score: 91,
    summary: "Host games and provide support in Portuguese. Relocation with visa and flights for Portuguese speakers moving abroad.",
    apply_url: "https://www.indeed.com/q-evolution-gaming-jobs.html"
  },
  {
    id: 214,
    title: "Portuguese Speaking Customer Success Specialist",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 26000,
    salary_max: 36000,
    currency: "EUR",
    location: "Canada (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Customer Success", "Support", "Relocation", "Bonuses"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "SmartRecruiters",
    match_score: 90,
    summary: "Ensure customer success in Portuguese. Full relocation support including visa and flights.",
    apply_url: "https://careers.smartrecruiters.com/Evolution"
  },
  {
    id: 215,
    title: "Portuguese Speaking Equipment Support (Part Time)",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "US (Relocation Provided with Visa & Flights)",
    type: "Part-time",
    tags: ["Equipment Support", "Gaming", "Visa Support", "Training"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Evolution Careers",
    match_score: 89,
    summary: "Support online casino equipment in Portuguese. Part-time with relocation, visa, and flights.",
    apply_url: "https://careers.evolution.com/usa/"
  },
  {
    id: 216,
    title: "Portuguese Speaking Floor Supervisor Support",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Mid Level",
    salary_min: 30000,
    salary_max: 40000,
    currency: "EUR",
    location: "Malta (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Floor Supervisor", "Support", "Relocation", "Leadership"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Indeed",
    match_score: 88,
    summary: "Supervise and support in Portuguese. Relocation with visa and flights for mid-level roles.",
    apply_url: "https://www.indeed.com/q-evolution-gaming-jobs.html"
  },
  {
    id: 217,
    title: "Portuguese Speaking Research Support",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["Portuguese", "English"],
    level: "Mid Level",
    salary_min: 35000,
    salary_max: 45000,
    currency: "EUR",
    location: "Worldwide (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Research", "Gaming", "Visa Sponsorship", "Relocation"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "LinkedIn",
    match_score: 87,
    summary: "Provide research support in Portuguese. Global relocation with visa and flights.",
    apply_url: "https://www.linkedin.com/jobs/evolution-gaming-jobs-worldwide"
  },

  // === FRENCH SPEAKING POSITIONS (IDs 168-177) ===
  {
    id: 168,
    title: "French Speaking Customer Service Representative",
    company: "Teleperformance",
    logoBg: "bg-blue-800",
    initials: "TP",
    languages: ["French", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Athens, Greece (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Customer Service", "Support", "Visa Sponsorship", "Flights Included"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Europe Language Jobs",
    match_score: 95,
    summary: "Provide customer support in French. Relocation package includes visa, flights, and accommodation for French speakers seeking to leave France.",
    apply_url: "https://www.europelanguagejobs.com/jobs-for-French-speakers"
  },
  {
    id: 169,
    title: "French Speaking Game Presenter",
    company: "Evolution",
    logoBg: "bg-slate-900",
    initials: "EVO",
    languages: ["French", "English"],
    level: "Entry Level",
    salary_min: 25000,
    salary_max: 35000,
    currency: "EUR",
    location: "Malta (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Gaming", "Live Casino", "Visa Support", "Accommodation"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Indeed",
    match_score: 96,
    summary: "Host live games in French. No experience needed; full relocation with visa, flights, and housing for French speakers moving abroad.",
    apply_url: "https://uk.indeed.com/q-visa-sponsorship-french-available-jobs.html"
  },
  {
    id: 170,
    title: "French Speaking Sales Representative",
    company: "Concentrix",
    logoBg: "bg-green-800",
    initials: "CX",
    languages: ["French", "English"],
    level: "Mid Level",
    salary_min: 30000,
    salary_max: 40000,
    currency: "EUR",
    location: "Barcelona, Spain (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Sales", "B2B", "Visa Assistance", "Relocation Support"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "ZipRecruiter",
    match_score: 94,
    summary: "Handle sales for French markets. Relocation with visa, flights, and accommodation assistance.",
    apply_url: "https://www.ziprecruiter.com/Jobs/Visa-Sponsorship-Relocation-French"
  },
  {
    id: 171,
    title: "French Speaking Content Moderator",
    company: "Majorel",
    logoBg: "bg-purple-800",
    initials: "MJ",
    languages: ["French", "English"],
    level: "Entry Level",
    salary_min: 22000,
    salary_max: 32000,
    currency: "EUR",
    location: "Lisbon, Portugal (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Content Moderation", "Social Media", "Visa Sponsorship", "Accommodation"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Glassdoor",
    match_score: 93,
    summary: "Moderate content in French. Relocation support including visa and flights for French speakers.",
    apply_url: "https://www.glassdoor.com/Job/france-visa-sponsorship-jobs-SRCH_IL.0,6_IN86_KO7,23.htm"
  },
  {
    id: 172,
    title: "French Logistics Coordinator with Visa Sponsorship",
    company: "Various",
    logoBg: "bg-gray-800",
    initials: "VA",
    languages: ["French", "English"],
    level: "Entry Level",
    salary_min: 25000,
    salary_max: 35000,
    currency: "EUR",
    location: "Europe (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Logistics", "Coordination", "Visa Support", "Flights"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Indeed",
    match_score: 92,
    summary: "Coordinate logistics in French. Visa sponsorship and relocation with flights for international moves.",
    apply_url: "https://www.indeed.com/q-french-logistics-visa-sponsorship-jobs-jobs.html"
  },
  {
    id: 173,
    title: "French Payroll Specialist with Relocation",
    company: "Various",
    logoBg: "bg-red-800",
    initials: "VA",
    languages: ["French", "English"],
    level: "Mid Level",
    salary_min: 30000,
    salary_max: 40000,
    currency: "EUR",
    location: "France/Europe (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Payroll", "Finance", "Visa Assistance", "Accommodation"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Jooble",
    match_score: 91,
    summary: "Handle payroll in French. Relocation support with visa and flights.",
    apply_url: "https://fr.jooble.org/emploi-french-payroll-relocation"
  },
  {
    id: 174,
    title: "French Speaking Business Development Representative",
    company: "Europe Language Jobs",
    logoBg: "bg-blue-900",
    initials: "ELJ",
    languages: ["French", "English"],
    level: "Entry Level",
    salary_min: 25000,
    salary_max: 35000,
    currency: "EUR",
    location: "Athens, Greece (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Business Development", "Sales", "Visa Support", "Flights"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Europe Language Jobs",
    match_score: 90,
    summary: "Develop business in French. Relocation with visa, flights, and accommodation.",
    apply_url: "https://www.europelanguagejobs.com/jobs-for-French-speakers"
  },
  {
    id: 175,
    title: "French Speaking Work Abroad Opportunities",
    company: "LinkedIn",
    logoBg: "bg-blue-900",
    initials: "LI",
    languages: ["French", "English"],
    level: "Entry Level",
    salary_min: 55000,
    salary_max: 90000,
    currency: "USD",
    location: "Various Abroad (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Various", "Work Abroad", "Visa Sponsorship", "Accommodation"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "LinkedIn",
    match_score: 89,
    summary: "Various roles for French speakers abroad. Paid relocation, visa, and temporary housing.",
    apply_url: "https://www.linkedin.com/pulse/work-abroad-2025-jobs-pay-your-flight-accommodation-fqh3e"
  },
  {
    id: 176,
    title: "French Speaking Hotel Jobs in Europe",
    company: "TerraTern",
    logoBg: "bg-green-900",
    initials: "TT",
    languages: ["French", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Europe (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Hotel", "Hospitality", "Visa Support", "Benefits"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "TerraTern",
    match_score: 88,
    summary: "Hotel jobs for French speakers. Sponsored visa, accommodation, and flights.",
    apply_url: "https://terratern.com/blog/free-visa-hotel-job-in-europe/"
  },
  {
    id: 177,
    title: "French Speaking Visa Sponsorship Roles",
    company: "Glassdoor",
    logoBg: "bg-gray-800",
    initials: "GD",
    languages: ["French", "English"],
    level: "Various",
    salary_min: 30000,
    salary_max: 50000,
    currency: "EUR",
    location: "France/Europe (Relocation Provided with Visa & Flights)",
    type: "Full-time",
    tags: ["Various", "Sponsorship", "Relocation", "Support"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Glassdoor",
    match_score: 87,
    summary: "Multiple roles with visa sponsorship for French speakers. Relocation with flights and support.",
    apply_url: "https://www.glassdoor.com/Job/france-visa-sponsorship-jobs-SRCH_IL.0,6_IN86_KO7,23.htm"
  },

  // === ADDITIONAL MULTILINGUAL BPO POSITIONS (IDs 189-198) ===
  {
    id: 189,
    title: "Multilingual Customer Support Representative",
    company: "Teleperformance Greece",
    logoBg: "bg-blue-800",
    initials: "TPG",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Greece (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["BPO", "Customer Service", "Visa Sponsorship", "No Experience Needed"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Teleperformance Careers",
    match_score: 95,
    summary: "Provide multilingual customer support. Entry-level with full relocation package including visa, flights, and accommodation for international candidates seeking to move abroad.",
    apply_url: "https://tp-greece.com/"
  },
  {
    id: 190,
    title: "Multilingual Content Moderator",
    company: "Majorel",
    logoBg: "bg-purple-800",
    initials: "MJ",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 22000,
    salary_max: 32000,
    currency: "EUR",
    location: "Europe (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Content Moderation", "BPO", "Visa Support", "Training Provided"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Majorel Careers",
    match_score: 94,
    summary: "Moderate content in multiple languages. Relocation support with visa, flights, and accommodation for entry-level roles.",
    apply_url: "https://www.majorel.com/careers/"
  },
  {
    id: 191,
    title: "Multilingual Customer Success Specialist",
    company: "Concentrix",
    logoBg: "bg-green-800",
    initials: "CX",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Portugal/Greece (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["BPO", "Customer Success", "Visa Assistance", "Relocation Package"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Concentrix Careers",
    match_score: 93,
    summary: "Handle customer success in multiple languages. Full relocation with visa, flights, and accommodation.",
    apply_url: "https://jobs.concentrix.com/"
  },
  {
    id: 192,
    title: "Multilingual Trust & Safety Specialist",
    company: "TikTok Trust & Safety",
    logoBg: "bg-red-800",
    initials: "TT",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 25000,
    salary_max: 35000,
    currency: "EUR",
    location: "Europe (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Content Moderation", "Safety", "Visa Sponsorship", "No Experience"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "TikTok Careers",
    match_score: 92,
    summary: "Ensure platform safety in multiple languages. Relocation support with visa, flights, and accommodation for entry-level candidates.",
    apply_url: "https://careers.tiktok.com/"
  },
  {
    id: 193,
    title: "Multilingual Customer Service Agent",
    company: "Agoda",
    logoBg: "bg-orange-800",
    initials: "AG",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 22000,
    salary_max: 32000,
    currency: "EUR",
    location: "Europe (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Customer Service", "BPO", "Visa Support", "Training"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Agoda Careers",
    match_score: 91,
    summary: "Provide customer service in multiple languages. Full relocation with visa, flights, and accommodation.",
    apply_url: "https://careersatagoda.com/"
  },
  {
    id: 194,
    title: "Multilingual Booking Support Specialist",
    company: "Booking.com",
    logoBg: "bg-blue-900",
    initials: "BC",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 24000,
    salary_max: 34000,
    currency: "EUR",
    location: "Netherlands (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Support", "Travel", "Visa Assistance", "Relocation Bonus"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Booking.com Careers",
    match_score: 90,
    summary: "Support bookings in multiple languages. Relocation package with visa, flights, and accommodation.",
    apply_url: "https://careers.booking.com/"
  },
  {
    id: 195,
    title: "Multilingual Game Development Support",
    company: "Ubisoft",
    logoBg: "bg-red-800",
    initials: "UB",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 30000,
    salary_max: 40000,
    currency: "EUR",
    location: "Europe (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Gaming", "Development", "Visa Sponsorship", "No Experience"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Ubisoft Careers",
    match_score: 89,
    summary: "Support game development in multiple languages. Full relocation with visa, flights, and accommodation.",
    apply_url: "https://www.ubisoft.com/en-us/company/careers"
  },
  {
    id: 196,
    title: "Multilingual Entry-Level Roles",
    company: "Europe Language Jobs",
    logoBg: "bg-blue-900",
    initials: "ELJ",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Europe (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Various", "Support", "Visa Support", "Training"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Europe Language Jobs",
    match_score: 88,
    summary: "Various multilingual roles with relocation, visa, flights, and accommodation.",
    apply_url: "https://www.europelanguagejobs.com/"
  },
  {
    id: 197,
    title: "Multilingual Customer Support",
    company: "Job Squad",
    logoBg: "bg-purple-800",
    initials: "JS",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 22000,
    salary_max: 32000,
    currency: "EUR",
    location: "Portugal (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Customer Support", "BPO", "Visa Assistance", "Relocation"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Job Squad",
    match_score: 87,
    summary: "Provide multilingual support. Relocation with visa, flights, and accommodation.",
    apply_url: "https://www.jobsqd.com/"
  },
  {
    id: 198,
    title: "Multilingual Roles with Relocation",
    company: "Foundever",
    logoBg: "bg-red-800",
    initials: "FE",
    languages: ["Multiple Languages", "English"],
    level: "Entry Level",
    salary_min: 20000,
    salary_max: 30000,
    currency: "EUR",
    location: "Europe (Relocation Provided with Visa, Flights & Accommodation)",
    type: "Full-time",
    tags: ["Support", "BPO", "Visa Sponsorship", "Entry Level"],
    posted_at: "Recent",
    featured: true,
    ai_verified: true,
    source: "Foundever Careers",
    match_score: 86,
    summary: "Entry-level multilingual roles with full relocation, visa, flights, and accommodation.",
    apply_url: "https://jobs.foundever.com/"
  }
];

export default JOBS_DATA;
